### ISSUE TITLE
USB error "-9" when initializing T500RS

### ISSUE THREAD

**Issue by hoover67** [her001/tmdrv#6]
When running the script with python 2.7 or python3 as "root", I'm seeing the following errors (wheel disconnected from power between attempts with 2.7 and 3: 

```
# python tmdrv.py -d thrustmaster_t500rs
Traceback (most recent call last):
  File "tmdrv.py", line 111, in <module>
    initialize(args.device)
  File "tmdrv.py", line 45, in initialize
    m['data'],
  File "tmdrv.py", line 92, in _control_init
    data,
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 1453, in controlWrite
    sizeof(data), timeout)
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 1429, in _controlTransfer
    mayRaiseUSBError(result)
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/local/lib/python2.7/dist-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorPipe: LIBUSB_ERROR_PIPE [-9]

# ATTEMPT using Python 3: 
 # python3 tmdrv.py -d thrustmaster_t500rs
Traceback (most recent call last):
  File "tmdrv.py", line 111, in <module>
    initialize(args.device)
  File "tmdrv.py", line 45, in initialize
    m['data'],
  File "tmdrv.py", line 92, in _control_init
    data,
  File "/usr/local/lib/python3.5/dist-packages/usb1/__init__.py", line 1453, in controlWrite
    sizeof(data), timeout)
  File "/usr/local/lib/python3.5/dist-packages/usb1/__init__.py", line 1429, in _controlTransfer
    mayRaiseUSBError(result)
  File "/usr/local/lib/python3.5/dist-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/usr/local/lib/python3.5/dist-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorPipe: LIBUSB_ERROR_PIPE [-9]
```
This is a mere cosmetical issue I guess because the wheel and pedals work fine in spite of these console messages. 

All the best,

Uwe

**Comment by her001** [comment]
Thanks for the report!

This is a low priority for me, but I'll investigate this later to see if I can find a better way to handle the USB "disconnect" which happens when the device switches modes.

**Comment by her001** [comment]
So this was actually a problem that was fixed before in f494ef2d2f4d8ba802f670f081c504329e66c0e2, but I removed the fix as it didn't seem to be needed anymore on the version of libusb that I used.

The previous behavior has been restored in ce4c172c9d255c8313db4a2343bd775d0ad91a1d. Could you test it? It is expected that everything will work the same, but without the error.

**Comment by hoover67** [comment]
Looking good, the USB exception has disappeared, now I'm getting an error from "jscal": 

```
python3 /home/hoover/src/tmdrv/tmdrv.py -d thrustmaster_t500rsjscal: can't open joystick device: No such file or directory
Traceback (most recent call last):
  File "/home/hoover/src/tmdrv/tmdrv.py", line 117, in <module>
    initialize(args.device)
  File "/home/hoover/src/tmdrv/tmdrv.py", line 74, in initialize
    _jscal(device.jscal, "/dev/input/by-id/" + device.dev_by_id)
  File "/home/hoover/src/tmdrv/tmdrv.py", line 81, in _jscal
    check_call(['jscal', '-s', configuration, device_file])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['jscal', '-s', '6,1,0,16439,16439,32879,32879,1,0,511,511,1054724,1052655,1,0,512,512,1052655,1052655,1,0,510,510,1052655,1050595,1,0,0,0,536854528,536854528,1,0,0,0,536854528,536854528', '/dev/input/by-id/usb-Thrustmaster_TRS_Racing_wheel-joystick']' returned non-zero exit status 1

```

The device passed as an argument to jscal exists however 

 ```
ls -l /dev/input/by-id/usb-Thrustmaster_TRS_Racing_wheel-joystick 
lrwxrwxrwx 1 root root 6 Jun 11 17:53 /dev/input/by-id/usb-Thrustmaster_TRS_Racing_wheel-joystick -> ../js3

```

All the best, Uwe

**Comment by her001** [comment]
Thanks for testing, I'm going to close this issue then.

It is strange that jscal is acting up. Could you please make a new issue for that?
